Numpy
numpy is short for Numerical Python.

Numerical data
Datasets come from a wide range of sources and formats: it could be collections of numerical measurements, text corpus, images, audio clips, or basically anything. No matter the format, the first step in data science is to transform it into array of numbers



In [1]:
heights = [
    189,150,135,135,165,123,142,163,135,
    143,163,136,124,164,173,178,185,174,
    182,142,122,183,181,191,193,102,192,
    144,122,173,171,123,172,178,103,100,
    136,193,123,161,171,177,142,122,128
]

to know the number of presidents that are taller than 188cm, we could iterate through the list, compare each element against 188, and increase the count by 1 as the criteria is met

In [4]:
for i in heights:
    if i >= 188:
        count = []
        counts = 0
        counts += 1
        count.append(i)
        
        
count, counts

([193], 1)

In [5]:
import numpy as np

In [10]:
heights_arr = np.array(heights)
#print((heights_arr > 150).sum())

In [11]:
heights_arr

array([189, 150, 135, 135, 165, 123, 142, 163, 135, 143, 163, 136, 124,
       164, 173, 178, 185, 174, 182, 142, 122, 183, 181, 191, 193, 102,
       192, 144, 122, 173, 171, 123, 172, 178, 103, 100, 136, 193, 123,
       161, 171, 177, 142, 122, 128])

In [14]:
total = (heights_arr > 150).sum()
total

23

size and shape

size is to get the length of array

In [15]:
heights_arr.size

45

for shape, the output is a tuple. shape is to get the dimension of array

In [16]:
heights_arr.shape

(45,)

Reshape

In [17]:
ages = [
    53,34,23,56,36,33,76,45,74,
    47,43,85,44,89,53,46,23,47,
    85,43,68,57,85,42,35,78,58,
    47,79,90,67,57,89,97,98,56,
    75,46,78,99,76,43,36,67,47
]

In [20]:
heights_and_ages = heights + ages
heights_and_ages_arr = np.array(heights_and_ages)
heights_and_ages_arr

array([189, 150, 135, 135, 165, 123, 142, 163, 135, 143, 163, 136, 124,
       164, 173, 178, 185, 174, 182, 142, 122, 183, 181, 191, 193, 102,
       192, 144, 122, 173, 171, 123, 172, 178, 103, 100, 136, 193, 123,
       161, 171, 177, 142, 122, 128,  53,  34,  23,  56,  36,  33,  76,
        45,  74,  47,  43,  85,  44,  89,  53,  46,  23,  47,  85,  43,
        68,  57,  85,  42,  35,  78,  58,  47,  79,  90,  67,  57,  89,
        97,  98,  56,  75,  46,  78,  99,  76,  43,  36,  67,  47])

In [21]:
heights_and_ages_arr.shape

(90,)

this produces one long array. it would be clearer if we could align height and age for each president and reorganize the data into a 2 by 45 matrix where the first row contains all heights and the second row contains ages, to achieve this, a new array can be created by calling numpy.ndarray.reshape with new dimensions specified in a tuple

In [24]:
heights_and_ages_arr.reshape(2,45)

array([[189, 150, 135, 135, 165, 123, 142, 163, 135, 143, 163, 136, 124,
        164, 173, 178, 185, 174, 182, 142, 122, 183, 181, 191, 193, 102,
        192, 144, 122, 173, 171, 123, 172, 178, 103, 100, 136, 193, 123,
        161, 171, 177, 142, 122, 128],
       [ 53,  34,  23,  56,  36,  33,  76,  45,  74,  47,  43,  85,  44,
         89,  53,  46,  23,  47,  85,  43,  68,  57,  85,  42,  35,  78,
         58,  47,  79,  90,  67,  57,  89,  97,  98,  56,  75,  46,  78,
         99,  76,  43,  36,  67,  47]])