Numpy
numpy is short for Numerical Python.

Numerical data
Datasets come from a wide range of sources and formats: it could be collections of numerical measurements, text corpus, images, audio clips, or basically anything. No matter the format, the first step in data science is to transform it into array of numbers



In [2]:
heights = [
    189,150,135,135,165,123,142,163,135,
    143,163,136,124,164,173,178,185,174,
    182,142,122,183,181,191,193,102,192,
    144,122,173,171,123,172,178,103,100,
    136,193,123,161,171,177,142,122,128
]

to know the number of presidents that are taller than 188cm, we could iterate through the list, compare each element against 188, and increase the count by 1 as the criteria is met

In [3]:
for i in heights:
    if i >= 188:
        count = []
        counts = 0
        counts += 1
        count.append(i)
        
        
count, counts

([193], 1)

In [4]:
import numpy as np

In [5]:
heights_arr = np.array(heights)
#print((heights_arr > 150).sum())

In [6]:
heights_arr

array([189, 150, 135, 135, 165, 123, 142, 163, 135, 143, 163, 136, 124,
       164, 173, 178, 185, 174, 182, 142, 122, 183, 181, 191, 193, 102,
       192, 144, 122, 173, 171, 123, 172, 178, 103, 100, 136, 193, 123,
       161, 171, 177, 142, 122, 128])

In [7]:
total = (heights_arr > 150).sum()
total

23

size and shape

size is to get the length of array

In [8]:
heights_arr.size

45

for shape, the output is a tuple. shape is to get the dimension of array

In [9]:
heights_arr.shape

(45,)

Reshape

In [10]:
ages = [
    53,34,23,56,36,33,76,45,74,
    47,43,85,44,89,53,46,23,47,
    85,43,68,57,85,42,35,78,58,
    47,79,90,67,57,89,97,98,56,
    75,46,78,99,76,43,36,67,47
]

In [11]:
heights_and_ages = heights + ages
heights_and_ages_arr = np.array(heights_and_ages)
heights_and_ages_arr

array([189, 150, 135, 135, 165, 123, 142, 163, 135, 143, 163, 136, 124,
       164, 173, 178, 185, 174, 182, 142, 122, 183, 181, 191, 193, 102,
       192, 144, 122, 173, 171, 123, 172, 178, 103, 100, 136, 193, 123,
       161, 171, 177, 142, 122, 128,  53,  34,  23,  56,  36,  33,  76,
        45,  74,  47,  43,  85,  44,  89,  53,  46,  23,  47,  85,  43,
        68,  57,  85,  42,  35,  78,  58,  47,  79,  90,  67,  57,  89,
        97,  98,  56,  75,  46,  78,  99,  76,  43,  36,  67,  47])

In [12]:
heights_and_ages_arr.shape

(90,)

this produces one long array. it would be clearer if we could align height and age for each president and reorganize the data into a 2 by 45 matrix where the first row contains all heights and the second row contains ages, to achieve this, a new array can be created by calling numpy.ndarray.reshape with new dimensions specified in a tuple

In [13]:
heights_and_ages_arr.reshape(2,45)

array([[189, 150, 135, 135, 165, 123, 142, 163, 135, 143, 163, 136, 124,
        164, 173, 178, 185, 174, 182, 142, 122, 183, 181, 191, 193, 102,
        192, 144, 122, 173, 171, 123, 172, 178, 103, 100, 136, 193, 123,
        161, 171, 177, 142, 122, 128],
       [ 53,  34,  23,  56,  36,  33,  76,  45,  74,  47,  43,  85,  44,
         89,  53,  46,  23,  47,  85,  43,  68,  57,  85,  42,  35,  78,
         58,  47,  79,  90,  67,  57,  89,  97,  98,  56,  75,  46,  78,
         99,  76,  43,  36,  67,  47]])

data type
another characteristic about numpy array is that it is homogenous, meaning each element must be of the same data type.
for example, in heights_arr, we recorded all heights in whole numbers, thus each element is stored as an integer in  the array. to check the data type, use numpy.ndarray.dtype

In [15]:
heights_and_ages_arr.dtype

dtype('int32')

In [16]:
a = np.array([1,2,3,4])
a.shape

(4,)

In [17]:
a.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

lesson 2 : Linear regression
what is machine learning?
machine learning is a subject of data science, is the scientific study of computational algorithms and statistical models to perform specific tasks through patterns and inference instead of explicit instructions. machine learning can be described a set of tools to build models on data. 

supervised and unsupervised learning
in machine learning, we talk about supervised and unsupervised learning. supervised learning is when we have a known target (also called label) based on past data ( for example, predicting what price of house will sell for) and unsupervised learning is when there isn't a known past answer (for example, determining the topics discussed in restaurant reviews)

scikit-learn
scikit-learn, one of the best known machine learning libraries in python for machine learning, implements a large number of commonly used algorithms. regardless of the type of algorithm, the syntax follows the same workflow

import -> instantiate -> fit -> predict

once the basic use and syntax of scikit learn is understood for one model, switching to a new algorithm is straightforward. 

# instantiate is the part where you create the model ( by choosing an algorithm ) and then assign it to a variable. in other words, you create an INSTANCE 
for example
model = linearRegression()

Linear Regression
it is a simple supervised learning model. Linear regression fits a straight line to data
mathematically:
y = b + mx

where b is the intercept and m is the slope, x is a feature or an input, whereas y is label or an output. our job is to find m and b such that the errors are minimised


correlation matrix
to understand the relationship among features (columns), a correlation matrix is very useful in the exploratory data analysis. correlation measures linear relationships between variables. we can construct a correlation matrix to show correlation coefficients between variables it is symmetric where each element is a correlation coefficient ranging from -1 and 1. a value near 1 indicates a strong positive correlation between variables. we can create a correlation matrix using the 'corr' function

two variables are perfectly correlated when the correlation coefficient is between 0.9-1 and -0.9 - -1

# it would worth noting that a negative correlation does not imply the two features of the data are unrelated to one another. rather, as the correlation approaches 0, there is less of a relationship between the features. in fact, if the correlation is negative, the closer you get to -1, the more related the features are! the parity ( positive or negative) just indicates the type of relationship the features share.

# close to +1 -> as one variable increases, so does the other (direct relationship)
# close to -1 -> as one variable increases, the other decreases (inverse relationship)
# close to 0 -> you can't expect an increase in one variable to predict the other's behavior well (no/minimal relationship)

# the values along the diagonal of the correlation matrix are all 1 because each column is identically correlated to itself

In [24]:
from sklearn.datasets import load_breast_cancer

In [25]:
breast = load_breast_cancer()

In [26]:
breast

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [27]:
corr_matrix = breast.corr().round(2)

AttributeError: corr